<?php 

/*function dashboard_total_members_block(){
drupal_add_js(array('aflWidgets' => array('total_members' => url('alumni/widget/ajax/total-members'))), 'setting');
  drupal_add_js(array('aflWidgets' => array('dm_visible_valu' => afl_variable_get('afl_widgets_downline_members_visible_valu','t'))), 'setting');
  return theme('html_tag', array('element' => array('#tag' => 'div','#attributes' => array('class' => array('afl-widget-panel')),'#value' => 'Loading..')));
}*/